### PR TITLE
Include original error

### LINKED ISSUE #39: Allow thrown object to populate SubmissionError messages
Right now, you can only pass custom messages if you put them under an `errors` key (it's built that way because it matches lp-request's `HTTPError`). However, we could have it fallback to the full object if that key is not present.

Relevant line: https://github.com/LaunchPadLab/lp-form/blob/master/src/middleware/wrapSubmissionErrors.js#L15

cc @chawes13

### PR DESCRIPTION
**Pull request by chawes13**
Resolves #39

### CODE REVIEW

**Comment by chawes13** [comment]
This should be non-breaking (i.e., not a major change) as the resulting error object provided to `redux-form`'s `onSubmitFail` is the exact same (takes the `errors` property from the thrown `SubmissionError`). Additionally, the property is additive on the `SubmissionError` object, so it's not likely that existing projects have logic based on the `error` property of the third argument provided to `onSubmitFail` (which is the `SubmissionError` object)

**Comment by dpikt** [comment]
Sounds good to me. My only concern is there might be confusion around which properties are "native" to SubmissionError- `errors` is but `error` isn't. Could be resolved by good documentation or perhaps making `error` harder to access (like `meta.error`).

**Comment by chawes13** [comment]
@dpikt That's fair. I think it could also be easier to confuse formwide `_error` with `error` on the `SubmissionError`. 

I'm in favor of `meta.error` as I think that's pretty descriptive. PR with update and documentation coming shortly.

**Comment by chawes13** [comment]
@dpikt Ready for review

**Pull request merged**
